manual testing

diff --git a/.github/workflows/test_enforcement.yml b/.github/workflows/test_enforcement.yml
--- a/.github/workflows/test_enforcement.yml
+++ b/.github/workflows/test_enforcement.yml
@@ -11,14 +11,26 @@ jobs:
   enforce-test:
     runs-on: ubuntu-latest
     steps:
+      - name: Get PR labels
+        id: pr-labels
+        uses: joerick/pr-labels-action@v1.0.6
+
       - id: files
         uses: jitterbit/get-changed-files@v1
-      - run: |
+
+      - name: Check for tests manual
+        if: !contains(steps.pr-labels.outputs.labels, ' tests-not-required ')
+        run: |
+          file-pattern='tests/.*/*.py'
           for changed_file in ${{ steps.files.outputs.all }}; do
-            echo "Do something with this ${changed_file}."
+            if [[ "$changed_file" =~ "$file-pattern" ]]; then
+              exit 0
+            fi
           done
-          
-      - name: "Check for tests"
+          echo "Missing a tests in $file-pattern; Please add at least one test or apply the tests not required label to the pull request"
+          exit 1
+
+      - name: Check for tests
         uses: brettcannon/check-for-changed-files@v1
         with:
           file-pattern: |
